name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    # - run: pm2 reload next-js
    - run: sudo docker-compose stop -t 1 nextjs
    - run: sudo docker-compose build nextjs
    - run: sudo docker-compose up --no-start nextjs
    - run: sudo docker-compose start nextjs
      env:
        CI: true